=== 0xNeffarion/osrsreboxed-db/test/item_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",

    "title": "Item",
    "type": "object",
    "properties": {
      "id": {
        "type": "integer"
      },
      "name": {
        "type": "string"
      },
      "members": {
        "type": "boolean"
      },
      "tradeable": {
        "type": ["boolean", "null"]
      },
      "tradeable_on_ge": {
        "type": "boolean"
      },
      "stackable": {
        "type": "boolean"
      },
      "noted": {
        "type": "boolean"
      },
      "noteable": {
        "type": "boolean"
      },
      "linked_id": {
        "type": ["integer", "null"]
      },
      "equipable": {
        "type": "boolean"
      },
      "cost": {
        "type": "integer"
      },
      "lowalch": {
        "type": "integer"
      },
      "highalch": {
        "type": "integer"
      },
      "weight": {
        "type": ["number", "null"]
      },
      "buy_limit": {
        "type": ["integer", "null"]
      },
      "quest_item": {
        "type": ["boolean", "null"]
      },
      "release_date": {
        "type": ["string", "null"]
      },
      "examine": {
        "type": ["string", "null"]
      },
      "url": {
        "type": ["string", "null"]
      }
    }
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/9984.json
{
  "id": 9984,
  "name": "Skewered bird meat",
  "tradeable": false,
  "stackable": false,
  "noteable": true,
  "equipable": false,
  "members": true,
  "weight": 1.65,
  "buy_limit": -1,
  "quest_item": true,
  "release_date": "21 November 2006",
  "cost": 81,
  "lowalch": 32,
  "highalch": 48,
  "examine": "Skewered bird meat.",
  "url": "http://2007.runescape.wikia.com/wiki/Skewered_bird_meat"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/19426.json
{
    "id": 19426,
    "name": "Sanfew serum(3)",
    "members": false,
    "tradeable": true,
    "tradeable_on_ge": false,
    "stackable": false,
    "noted": false,
    "noteable": false,
    "linked_id": null,
    "equipable": false,
    "cost": 0,
    "lowalch": 0,
    "highalch": 0,
    "weight": 0.0,
    "buy_limit": 2000,
    "quest_item": null,
    "release_date": "13 March 2007",
    "examine": "3 doses of Sanfew Serum.",
    "url": "https://oldschool.runescape.wiki/w/Sanfew_serum"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/17989.json
{
    "id": 17989,
    "name": "Red toad",
    "members": false,
    "tradeable": false,
    "stackable": false,
    "noted": false,
    "noteable": false,
    "equipable": false,
    "cost": 0,
    "lowalch": 0,
    "highalch": 0,
    "weight": 0.0,
    "buy_limit": null,
    "quest_item": [
        "Mourning's Ends Part I"
    ],
    "release_date": "19 July 2005",
    "examine": [
        "A red dye filled toad."
    ],
    "url": "http://oldschoolrunescape.wikia.com/wiki/Red_toad"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/10817.json
{
    "id": 10817,
    "name": "Raw yak meat",
    "members": true,
    "tradeable": false,
    "stackable": true,
    "noted": true,
    "noteable": true,
    "equipable": false,
    "cost": 2,
    "lowalch": 0,
    "highalch": 1,
    "weight": 3.0,
    "buy_limit": null,
    "quest_item": null,
    "release_date": "06 February 2007",
    "examine": [
        "I need to cook this."
    ],
    "url": "http://oldschoolrunescape.wikia.com/wiki/Raw_yak_meat"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/21865.json
{
    "id": 21865,
    "name": "Fine mesh net",
    "members": false,
    "tradeable": false,
    "stackable": false,
    "noted": false,
    "noteable": false,
    "equipable": false,
    "cost": 1,
    "lowalch": 0,
    "highalch": 0,
    "weight": 0.0,
    "buy_limit": null,
    "quest_item": null,
    "release_date": "11 December 2017",
    "examine": [
        "Only the most delicious nets can catch sprites."
    ],
    "url": "https://oldschool.runescape.wiki/w/Fine_mesh_net"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/1066.json
{
    "id": 1066,
    "name": "Green d'hide vamb",
    "members": false,
    "tradeable": false,
    "stackable": true,
    "noted": true,
    "noteable": true,
    "equipable": false,
    "cost": 2500,
    "lowalch": 1000,
    "highalch": 1500,
    "weight": 0.25,
    "buy_limit": null,
    "quest_item": null,
    "release_date": "01 December 2003",
    "examine": [
        "Vambraces made from 100% real dragonhide."
    ],
    "url": "http://oldschoolrunescape.wikia.com/wiki/Green_d%27hide_vamb"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/11497.json
{
  "id": 11497,
  "name": "Super def. mix(2)",
  "tradeable": true,
  "stackable": false,
  "noteable": true,
  "equipable": false,
  "members": true,
  "weight": 0.0,
  "buy_limit": -1,
  "quest_item": true,
  "release_date": "03 July 2007",
  "cost": 198,
  "lowalch": 79,
  "highalch": 118,
  "examine": "X dose(s) of fishy super Defence potion.",
  "url": "http://2007.runescape.wikia.com/wiki/Super_def._mix"
}
