=== 0xNeffarion/osrsreboxed-db/test/item_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",

    "title": "Item",
    "type": "object",
    "properties": {
      "id": {
        "type": "integer"
      },
      "name": {
        "type": "string"
      },
      "members": {
        "type": "boolean"
      },
      "tradeable": {
        "type": ["boolean", "null"]
      },
      "tradeable_on_ge": {
        "type": "boolean"
      },
      "stackable": {
        "type": "boolean"
      },
      "noted": {
        "type": "boolean"
      },
      "noteable": {
        "type": "boolean"
      },
      "linked_id": {
        "type": ["integer", "null"]
      },
      "equipable": {
        "type": "boolean"
      },
      "cost": {
        "type": "integer"
      },
      "lowalch": {
        "type": "integer"
      },
      "highalch": {
        "type": "integer"
      },
      "weight": {
        "type": ["number", "null"]
      },
      "buy_limit": {
        "type": ["integer", "null"]
      },
      "quest_item": {
        "type": ["boolean", "null"]
      },
      "release_date": {
        "type": ["string", "null"]
      },
      "examine": {
        "type": ["string", "null"]
      },
      "url": {
        "type": ["string", "null"]
      }
    }
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/11957.json
{
  "id": 11957,
  "name": "Extended antifire (1)",
  "tradeable": true,
  "stackable": false,
  "noteable": true,
  "equipable": false,
  "members": true,
  "weight": 0.0,
  "buy_limit": -1,
  "quest_item": true,
  "release_date": "27 March 2014",
  "cost": 110,
  "lowalch": 44,
  "highalch": 66,
  "examine": "X dose(s) of extended anti-firebreath potion.",
  "url": "http://2007.runescape.wikia.com/wiki/Extended_antifire"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/1997.json
{
  "id": 1997,
  "name": "Incomplete stew",
  "tradeable": false,
  "stackable": false,
  "noteable": true,
  "equipable": false,
  "members": false,
  "weight": 1.0,
  "buy_limit": -1,
  "quest_item": true,
  "release_date": "11 June 2001",
  "cost": 4,
  "lowalch": 1,
  "highalch": 2,
  "examine": "I need to add some meat too.",
  "url": "http://2007.runescape.wikia.com/wiki/Incomplete_stew"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/1839.json
{
  "id": 1839,
  "name": "Metal key",
  "tradeable": false,
  "stackable": false,
  "noteable": false,
  "equipable": false,
  "members": true,
  "weight": 0.0,
  "buy_limit": -1,
  "quest_item": true,
  "release_date": "14 April 2003",
  "cost": 1,
  "lowalch": 0,
  "highalch": 0,
  "examine": "This key is crudely made. It came from the mining camp Mercenary Captain (Provides access to the Desert Mining Camp).",
  "url": "http://2007.runescape.wikia.com/wiki/Metal_key"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/4429.json
{
  "id": 4429,
  "name": "Broken vane part",
  "tradeable": false,
  "stackable": false,
  "noteable": false,
  "equipable": false,
  "members": true,
  "weight": 0.0,
  "buy_limit": -1,
  "quest_item": true,
  "release_date": "28 February 2005",
  "cost": 1,
  "lowalch": 0,
  "highalch": 0,
  "examine": "This weather vane ornament is damaged.",
  "url": "http://2007.runescape.wikia.com/wiki/Broken_vane_part"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/949.json
{
    "id": 949,
    "name": "Bear fur",
    "members": false,
    "tradeable": false,
    "stackable": true,
    "noted": true,
    "noteable": true,
    "equipable": false,
    "cost": 10,
    "lowalch": 4,
    "highalch": 6,
    "weight": 3.0,
    "buy_limit": null,
    "quest_item": null,
    "release_date": "04 January 2001",
    "examine": [
        "This would make warm clothing."
    ],
    "url": "http://oldschoolrunescape.wikia.com/wiki/Bear_fur"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/21473.json
{
  "id": 21473,
  "name": "Teak seedling (w)",
  "tradeable": false,
  "stackable": false,
  "noteable": false,
  "equipable": false,
  "members": true,
  "weight": 0.0,
  "buy_limit": -1,
  "quest_item": true,
  "release_date": "07 September 2017",
  "cost": 1,
  "lowalch": 0,
  "highalch": 0,
  "examine": "A teak tree seed has been sown and watered in this plant pot.",
  "url": "http://2007.runescape.wikia.com/wiki/Teak_seedling_(w)"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/5852.json
{
    "id": 5852,
    "name": "Dwarven stout(m1)",
    "members": true,
    "tradeable": false,
    "stackable": true,
    "noted": true,
    "noteable": true,
    "equipable": false,
    "cost": 1,
    "lowalch": 0,
    "highalch": 0,
    "weight": 0.0,
    "buy_limit": null,
    "quest_item": null,
    "release_date": "11 July 2005",
    "examine": "This keg contains 1 pint of mature Dwarven Stout.",
    "url": "https://oldschool.runescape.wiki/w/Dwarven_stout(m)_(keg)"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/1784.json
{
    "id": 1784,
    "name": "Bucket of sand",
    "members": true,
    "tradeable": false,
    "stackable": true,
    "noted": true,
    "noteable": true,
    "equipable": false,
    "cost": 2,
    "lowalch": 0,
    "highalch": 1,
    "weight": 2.0,
    "buy_limit": null,
    "quest_item": null,
    "release_date": "18 March 2002",
    "examine": [
        "One of the ingredients for making glass."
    ],
    "url": "https://oldschool.runescape.wiki/w/Bucket_of_sand"
}
