=== 0xNeffarion/osrsreboxed-db/test/item_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",

    "title": "Item",
    "type": "object",
    "properties": {
      "id": {
        "type": "integer"
      },
      "name": {
        "type": "string"
      },
      "members": {
        "type": "boolean"
      },
      "tradeable": {
        "type": ["boolean", "null"]
      },
      "tradeable_on_ge": {
        "type": "boolean"
      },
      "stackable": {
        "type": "boolean"
      },
      "noted": {
        "type": "boolean"
      },
      "noteable": {
        "type": "boolean"
      },
      "linked_id": {
        "type": ["integer", "null"]
      },
      "equipable": {
        "type": "boolean"
      },
      "cost": {
        "type": "integer"
      },
      "lowalch": {
        "type": "integer"
      },
      "highalch": {
        "type": "integer"
      },
      "weight": {
        "type": ["number", "null"]
      },
      "buy_limit": {
        "type": ["integer", "null"]
      },
      "quest_item": {
        "type": ["boolean", "null"]
      },
      "release_date": {
        "type": ["string", "null"]
      },
      "examine": {
        "type": ["string", "null"]
      },
      "url": {
        "type": ["string", "null"]
      }
    }
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/8446.json
{
    "id": 8446,
    "name": "Fancy hedge",
    "members": true,
    "tradeable": false,
    "stackable": true,
    "noted": true,
    "noteable": true,
    "equipable": false,
    "cost": 25000,
    "lowalch": 10000,
    "highalch": 15000,
    "weight": null,
    "buy_limit": null,
    "quest_item": null,
    "release_date": null,
    "examine": "Like a living wall.",
    "url": "https://oldschool.runescape.wiki/w/Fancy_hedge"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/1959.json
{
  "id": 1959,
  "name": "Pumpkin",
  "tradeable": true,
  "stackable": false,
  "noteable": true,
  "equipable": false,
  "members": false,
  "weight": 0.5,
  "buy_limit": -1,
  "quest_item": true,
  "release_date": "31 October 2001",
  "cost": 30,
  "lowalch": 12,
  "highalch": 18,
  "examine": "Happy Halloween.",
  "url": "http://2007.runescape.wikia.com/wiki/Pumpkin"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/4436.json
{
  "id": 4436,
  "name": "Airtight pot",
  "tradeable": true,
  "stackable": false,
  "noteable": true,
  "equipable": false,
  "members": true,
  "weight": 0.5,
  "buy_limit": -1,
  "quest_item": true,
  "release_date": "28 February 2005",
  "cost": 10,
  "lowalch": 4,
  "highalch": 6,
  "examine": "This is pretty well sealed.",
  "url": "http://2007.runescape.wikia.com/wiki/Airtight_pot"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/9662.json
{
  "id": 9662,
  "name": "Shortcut key",
  "tradeable": false,
  "stackable": false,
  "noteable": false,
  "equipable": false,
  "members": true,
  "weight": 0.055,
  "buy_limit": -1,
  "quest_item": true,
  "release_date": "04 September 2006",
  "cost": 1,
  "lowalch": 0,
  "highalch": 0,
  "examine": "A key allowing a shortcut into the Sanguinesti region (Quick access through Meiyerditch).",
  "url": "http://2007.runescape.wikia.com/wiki/Shortcut_key"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/11689.json
{
  "id": 11689,
  "name": "Earth rune",
  "tradeable": false,
  "stackable": true,
  "noteable": false,
  "equipable": false,
  "members": false,
  "weight": 0.0,
  "buy_limit": 20000,
  "quest_item": true,
  "release_date": "04 January 2001",
  "cost": 1,
  "lowalch": 0,
  "highalch": 0,
  "examine": "One of the 4 basic elemental Runes.",
  "url": "http://2007.runescape.wikia.com/wiki/Earth_rune"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/6289.json
{
  "id": 6289,
  "name": "Snakeskin",
  "tradeable": true,
  "stackable": false,
  "noteable": true,
  "equipable": false,
  "members": true,
  "weight": 0.5,
  "buy_limit": -1,
  "quest_item": true,
  "release_date": "09 August 2005",
  "cost": 50,
  "lowalch": 20,
  "highalch": 30,
  "examine": "Scaley but not slimy!",
  "url": "http://2007.runescape.wikia.com/wiki/Snakeskin"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/4589.json
{
  "id": 4589,
  "name": "Keys",
  "tradeable": false,
  "stackable": false,
  "noteable": false,
  "equipable": false,
  "members": true,
  "weight": 0.0,
  "buy_limit": -1,
  "quest_item": true,
  "release_date": "04 April 2005",
  "cost": 1,
  "lowalch": 0,
  "highalch": 0,
  "examine": "Keys to the Mayor's house.",
  "url": "http://2007.runescape.wikia.com/wiki/Keys"
}

=== 0xNeffarion/osrsreboxed-db/docs/items-json/21217.json
{
  "id": 21217,
  "name": "Fresh easter egg",
  "tradeable": false,
  "stackable": false,
  "noteable": false,
  "equipable": false,
  "members": false,
  "weight": 0.0,
  "buy_limit": -1,
  "quest_item": true,
  "release_date": "06 April 2017",
  "cost": 1,
  "lowalch": 0,
  "highalch": 0,
  "examine": "A fresh flavoured Easter egg",
  "url": "http://2007.runescape.wikia.com/wiki/Fresh_easter_egg"
}
